[package]
name = "rust-exchange-adaptor-ws"
version = "0.1.0"
license = "MIT"
edition = "2018"

[dependencies]
futures = "0.3"
websocket-codec = { version = "0.5" }
websocket-lite = "*"
tokio = { version = "1", features = ["macros", "time", "io-std", "rt-multi-thread"] }
